// <auto-generated />
using System;
using KHCN.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace KHCN.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200714151409_14071")]
    partial class _14071
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_CapBac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_CapBac");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_CapQuanLy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_CapQuanLy");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_ChuanApDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_ChuanApDung");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_ChucDanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_ChucDanh");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_DonViCheTao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_DonViCheTao");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_GiaiDoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_GiaiDoan");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_GiaiDoanSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("ChiPhiNVL")
                        .HasColumnType("numeric");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaGiaiDoan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaSoNhiemVu")
                        .HasColumnType("text");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<string>("TenGiaiDoan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenNhiemVu")
                        .HasColumnType("text");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_GiaiDoanSanPham");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_HoSoDieuChinhKhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaSoNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayLapToTrinhXinPDDieuChinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayQDPheDuyetDieuChinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("QDPheDuyetDieuChinh")
                        .HasColumnType("text");

                    b.Property<string>("TenNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToTrinhXinPDDieuChinh")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_HoSoDieuChinhKhac");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_HoSoDieuChinhKinhPhi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("KinhPhiSauKhiDieuChinh")
                        .HasColumnType("numeric");

                    b.Property<string>("MaSoNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayLapToTrinhXinPDDieuChinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayQDPheDuyetDieuChinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("QDPheDuyetDieuChinh")
                        .HasColumnType("text");

                    b.Property<string>("TenNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToTrinhXinPDDieuChinh")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_HoSoDieuChinhKinhPhi");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_HoSoDieuChinhThoiGian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaSoNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayLapToTrinhXinPDDieuChinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayQDPheDuyetDieuChinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("QDPheDuyetDieuChinh")
                        .HasColumnType("text");

                    b.Property<string>("TenNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToTrinhXinPDDieuChinh")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_HoSoDieuChinhThoiGian");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_HoSoNghiemThu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BBHopHDNTCapTapDoan")
                        .HasColumnType("text");

                    b.Property<string>("BBHopHDNTCapVien")
                        .HasColumnType("text");

                    b.Property<string>("CongVanDNNTCapTapDoan")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaSoNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayHopHDNTCapTapDoan")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayHopHDXDCapVien")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayLapCongVanDNNTCapTapDoan")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayLapPhieuDNNghiemThuCapVien")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayQDCongNhanKetQua")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayQDLapHDNTCapTapDoan")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayQDLapHDNTCapVien")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhieuDNNghiemThuCapVien")
                        .HasColumnType("text");

                    b.Property<string>("QDCongNhanKetQua")
                        .HasColumnType("text");

                    b.Property<string>("QDLapHDNTCapTapDoan")
                        .HasColumnType("text");

                    b.Property<string>("QDLapHDNTCapVien")
                        .HasColumnType("text");

                    b.Property<string>("TenNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_HoSoNghiemThu");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_HoSoQuyetToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaSoNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayLapPhieuNhapKhoSP")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayQDPheDuyetHSQT")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhieuNhapKhoSP")
                        .HasColumnType("text");

                    b.Property<string>("QDPheDuyetHSQT")
                        .HasColumnType("text");

                    b.Property<string>("TenNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_HoSoQuyetToan");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_HoSoXetDuyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BBHopHDXDCapTapDoan")
                        .HasColumnType("text");

                    b.Property<string>("BBHopHDXDCapVien")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HoSoDuToan")
                        .HasColumnType("text");

                    b.Property<string>("MaSoNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayHopHDXDCapTapDoan")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayHopHDXDCapVien")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayLapHoSoDuToan")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayLapTaiLieuMRD")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayLapTaiLieuPRD")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayQDGiaoNhiemVu")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayQDLapHDXDCapTapDoan")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayQDLapHDXDCapVien")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayQDPheDuyet")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayThuyetMinhNhiemVu")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayTrinhXinPDChuTruong")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayTrinhXinPDNhiemVu")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhieuDangKy")
                        .HasColumnType("text");

                    b.Property<string>("QDGiaoNhiemVu")
                        .HasColumnType("text");

                    b.Property<string>("QDLapHDXDCapTapDoan")
                        .HasColumnType("text");

                    b.Property<string>("QDLapHDXDCapVien")
                        .HasColumnType("text");

                    b.Property<string>("QDPheDuyet")
                        .HasColumnType("text");

                    b.Property<string>("TaiLieuMRD")
                        .HasColumnType("text");

                    b.Property<string>("TaiLieuPRD")
                        .HasColumnType("text");

                    b.Property<string>("TenNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThuyetMinhNhiemVu")
                        .HasColumnType("text");

                    b.Property<string>("ToTrinhXinPDChuTruong")
                        .HasColumnType("text");

                    b.Property<string>("ToTrinhXinPDNhiemVu")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_HoSoXetDuyet");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_KinhPhiThucHien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("DuToanDieuChinh")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DuToanDuocDuyet")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GiaTriQuyetToan")
                        .HasColumnType("numeric");

                    b.Property<string>("MaSoNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NguonKinhPhi")
                        .HasColumnType("text");

                    b.Property<string>("TenNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TienTrinhDieuChinh")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_KinhPhiThucHien");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_LoaiNhiemVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_LoaiNhiemVu");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_Nganh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_Nganh");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_NhiemVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CapQuanLy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChuNhiemNV")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DonViChuTri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailChuNhiem")
                        .HasColumnType("text");

                    b.Property<int>("IdCapQuanLy")
                        .HasColumnType("integer");

                    b.Property<int>("IdChuNhiemNV")
                        .HasColumnType("integer");

                    b.Property<int>("IdDonViChuTri")
                        .HasColumnType("integer");

                    b.Property<int>("IdLoaiNhiemVu")
                        .HasColumnType("integer");

                    b.Property<int>("IdNganh")
                        .HasColumnType("integer");

                    b.Property<int>("IdTienDoThucHien")
                        .HasColumnType("integer");

                    b.Property<string>("LoaiNhiemVu")
                        .HasColumnType("text");

                    b.Property<string>("MaSoNhiemVu")
                        .HasColumnType("text");

                    b.Property<int>("NamHoanThanh")
                        .HasColumnType("integer");

                    b.Property<int>("NamPheDuyet")
                        .HasColumnType("integer");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TienDoThucHien")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_NhiemVu");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_PhongBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DonViCha")
                        .HasColumnType("text");

                    b.Property<int?>("DonViChaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_PhongBan");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ChuanApDung")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DonViCheTao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdChuanApDung")
                        .HasColumnType("integer");

                    b.Property<int>("IdDonViCheTao")
                        .HasColumnType("integer");

                    b.Property<int>("IdNganh")
                        .HasColumnType("integer");

                    b.Property<string>("MaGiaiDoan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaSoNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SanPhamTuongDuong")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("TenGiaiDoan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TinhNangChinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_SanPham");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_TaiLieuDinhKem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayFileName")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FileSize")
                        .HasColumnType("text");

                    b.Property<string>("Guid")
                        .HasColumnType("text");

                    b.Property<string>("Keyword")
                        .HasColumnType("text");

                    b.Property<int>("LoaiTaiLieu")
                        .HasColumnType("integer");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("text");

                    b.Property<string>("MaSoNhiemVu")
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_TaiLieuDinhKem");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_TaiLieuDinhKemDel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayFileName")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FileSize")
                        .HasColumnType("text");

                    b.Property<string>("Guid")
                        .HasColumnType("text");

                    b.Property<string>("Keyword")
                        .HasColumnType("text");

                    b.Property<int>("LoaiTaiLieu")
                        .HasColumnType("integer");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("text");

                    b.Property<string>("MaSoNhiemVu")
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_TaiLieuDinhKemDel");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_ThanhVienDeTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CapBac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChucDanh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DonVi")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("integer");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdCapBac")
                        .HasColumnType("integer");

                    b.Property<int>("IdChucDanh")
                        .HasColumnType("integer");

                    b.Property<int>("IdDonVi")
                        .HasColumnType("integer");

                    b.Property<int>("IdPhongBan")
                        .HasColumnType("integer");

                    b.Property<int>("IdTrinhDo")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayKyHD")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NhiemVu1")
                        .HasColumnType("text");

                    b.Property<string>("NhiemVu2")
                        .HasColumnType("text");

                    b.Property<string>("NhiemVu3")
                        .HasColumnType("text");

                    b.Property<string>("PhongBan")
                        .HasColumnType("text");

                    b.Property<int>("TrangThaiNV1")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThaiNV2")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThaiNV3")
                        .HasColumnType("integer");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_ThanhVienDeTai");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_ThoiGianThucHien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaSoNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TGBatDau")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TGGiaHanMoiNhat")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TGKetThuc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TenNhiemVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TienTrinhGiaHan")
                        .HasColumnType("integer");

                    b.Property<decimal>("TongTGThucHien")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_ThoiGianThucHien");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_TienDoThucHien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_TienDoThucHien");
                });

            modelBuilder.Entity("KHCN.Data.Entities.KHCN.KHCN_TrinhDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KHCN_TrinhDo");
                });

            modelBuilder.Entity("KHCN.Data.Entities.System.CMS_Api", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ControllerAction")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("IdModule")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("IdParent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("CMS_Api");
                });

            modelBuilder.Entity("KHCN.Data.Entities.System.CMS_Function", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ControllerAction")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("IdModule")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("IdParent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("CMS_Function");
                });

            modelBuilder.Entity("KHCN.Data.Entities.System.CMS_Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("CMS_Module");
                });

            modelBuilder.Entity("KHCN.Data.Entities.System.CMS_Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int?>("IdModule")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("IdParent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrderHint")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("CMS_Page");
                });

            modelBuilder.Entity("KHCN.Data.Entities.System.CMS_Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("CMS_Role");
                });

            modelBuilder.Entity("KHCN.Data.Entities.System.CMS_RoleApi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdApi")
                        .HasColumnType("integer");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("CMS_RoleApi");
                });

            modelBuilder.Entity("KHCN.Data.Entities.System.CMS_RoleFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdFunction")
                        .HasColumnType("integer");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("CMS_RoleFunction");
                });

            modelBuilder.Entity("KHCN.Data.Entities.System.CMS_RolePage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdPage")
                        .HasColumnType("integer");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("CMS_RolePage");
                });

            modelBuilder.Entity("KHCN.Data.Entities.System.CMS_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ActiveCode")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CMS_User");
                });

            modelBuilder.Entity("KHCN.Data.Entities.System.CMS_UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("CMS_UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
